[core]
max_cpus = "2"

[log]
output = "stdout"
mode = "dev"
level = "debug"

[http]
enabled_services = ["ocdavsvc"]
#enabled_middlewares = ["log", "trace", "auth", "cors"]
enabled_middlewares = ["log", "trace", "auth"]
network = "tcp"
address = "0.0.0.0:9998"

[http.middlewares.trace]
priority = 100
header = "x-trace"

[http.middlewares.log]
priority = 200

[http.middlewares.auth]
priority = 300
authsvc = "authsvc-ldap:9999"
credential_strategy = "basic"
token_strategy = "header"
token_writer = "header"
token_manager = "jwt"
skip_methods = ["/status.php"]

[http.middlewares.cors]
priority = 400

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.middlewares.auth.token_strategies.header]
header = "X-Access-Token"

[http.middlewares.auth.token_writers.header]
header = "X-Access-Token"


[http.services.ocdavsvc]
prefix = ""
chunk_folder = "/var/tmp/owncloud/chunks"
storageprovidersvc = "storageprovidersvc:9999"
enable_cors = true