[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "32"

[http]
enabled_services = ["prometheussvc", "ocdavsvc"]
network = "tcp"
address = "0.0.0.0:9998"

[http.services.prometheussvc]
prefix = "metrics"

[http.services.ocdavsvc]
prefix = "ocdav"
chunk_folder = "/var/tmp/owncloud/chunks"
storageprovidersvc = "127.0.0.1:9999"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
enabled_services = ["storagebrokersvc"]

[grpc.services.storagebrokersvc]
driver = "static"

[grpc.services.storagebrokersvc.static.rules]
"/" = "127.0.0.1:9999"
"123e4567-e89b-12d3-a456-426655440000" = "127.0.0.1:9999"

[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"

[grpc.services.storageprovidersvc.drivers.local]
root = "/data"

[grpc.services.storageprovidersvc.eos]
mgm = "root://nowhere.org"
root_uid = 0
root_gid = 0

[grpc.services.authsvc.auth_manager]
driver = "ldap"

[grpc.services.authsvc.auth_manager.ldap]
hostname = "openldap"
port = 636
base_dn = "dc=owncloudqa,dc=com"
filter = "(&(objectclass=inetorgperson)(uid=%s))"
bind_username = "cn=admin,dc=owncloudqa,dc=com"
bind_password = "admin"

[grpc.services.authsvc.token_manager]
driver = "jwt"


[grpc.services.authsvc.user_manager]
driver = "demo"

# not implemented yet
#[grpc.services.authsvc.user_manager.ldap]
#hostname = "openldap"
#port = 636
#base_dn = "dc=owncloudqa,dc=com"
#filter = "(&(objectclass=inetorgperson)(uid=%s))"
#bind_username = "cn=admin,dc=owncloudqa,dc=com"
#bind_password = "admin"
