[core]
log_file = "stderr"
log_mode = "dev"
max_cpus = "2"

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "stderr"
#tls_enabled = true
#tls_cert = "/etc/gridsecurity/host.cert"
#tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["storageprovidersvc"]
# TODO we need to authenticate the cs3 calls
enabled_interceptors = ["auth", "log", "trace"]

[grpc.interceptors.trace]
priority = 100
header = "x-trace"

[grpc.interceptors.log]
priority = 100

[grpc.interceptors.auth]
priority = 300
header = "X-Access-Token"
token_strategy = "header"
token_manager = "jwt"

[grpc.interceptors.auth.methods]
"/cs3.storageproviderv0alpha.StorageProviderService/Stat" = true

[grpc.interceptors.auth.token_strategies.header]
header = "X-Access-Token"

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.storageprovidersvc]
driver = "local"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"

[grpc.services.storageprovidersvc.drivers.local]
root = "/data"

[grpc.services.storageprovidersvc.eos]
mgm = "root://nowhere.org"
root_uid = 0
root_gid = 0
