[core]
max_cpus = "2"

[log]
output = "stdout"
mode = "dev"
level = "debug"

[http]
enabled_services = ["datasvc"]
enabled_middlewares = ["log", "trace", "auth"]
network = "tcp"
address = "0.0.0.0:9998"

[http.middlewares.trace]
priority = 100
header = "x-trace"

[http.middlewares.log]
priority = 200

[http.middlewares.auth]
# the storage provider is an 'internal' service, data requests should use the internal jwt token
priority = 300
token_strategy = "header"
token_manager = "jwt"
authsvc = "authsvc:9999" # not needed, the token should suffice
credential_strategy = "basic" # not needed, the token should suffice
token_writer = "header" # not needed, the token should suffice

[http.middlewares.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[http.middlewares.auth.token_strategies.header]
header = "X-Access-Token"

[http.middlewares.auth.token_writers.header]
header = "INVALID" # not needed, reading the token should suffice

[http.services.datasvc]
driver = "eos"
prefix = "data"
temp_folder = "/var/tmp/"

[http.services.datasvc.drivers.eos]
namespace = "/eos/dockertest/"
master_url = "root://eos-mgm-test.eoscluster.cern.ch"
root_uid = 0
root_gid = 0

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "stderr"
#tls_enabled = true
#tls_cert = "/etc/gridsecurity/host.cert"
#tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["storageprovidersvc", "usershareprovidersvc"]
# TODO we need to authenticate the cs3 calls
enabled_interceptors = ["auth", "log", "trace"]

[grpc.interceptors.trace]
priority = 100
header = "x-trace"

[grpc.interceptors.log]
priority = 100

[grpc.interceptors.auth]
priority = 300
# TODO grpc 'headers' are stored as google.golang.org/grpc/metadata ... needs better naming, this is too confusing
# keys for grpc metadata are always lowercase, so interceptors headers need to use lowercase.
header = "x-access-token"
token_strategy = "header"
token_manager = "jwt"

[grpc.interceptors.auth.token_strategies.header]
# TODO not needed? would need to be lowerase anyway
header = "X-Access-Token"

[grpc.interceptors.auth.token_managers.jwt]
secret = "Pive-Fumkiu4"

[grpc.services.storageprovidersvc]
driver = "eos"
mount_path = "/"
mount_id = "123e4567-e89b-12d3-a456-426655440000"
data_server_url = "http://storageprovidersvc:9998/data"

[grpc.services.storageprovidersvc.available_checksums]
md5   = 100
unset = 1000

[grpc.services.storageprovidersvc.drivers.eos]
namespace = "/eos/dockertest/"
master_url = "root://eos-mgm-test.eoscluster.cern.ch"

[grpc.services.usershareprovidersvc]
driver = "eos"

[grpc.services.usershareprovidersvc.drivers.eos]
namespace = "/eos/dockertest/"
master_url = "root://eos-mgm-test.eoscluster.cern.ch"